---
stages:
  - update
  - lint
  - lsif
  - test
  - publish

variables:
  PIP_CACHE_DIR: '${CI_PROJECT_DIR}/.cache/pip'

cache:
  key: '${CI_JOB_NAME}'
  paths:
    - .cache/pip
    - .pnpm-store
    - .venv

include:
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/eslint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/prettier.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/python/bandit.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/python/black.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/python/flake8.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/python/mypy.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/python/pydocstyle.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/python/pylint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/shellcheck.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/yamllint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lsif/python.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/semantic-release.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/test/python.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/update/project.gitlab-ci.yml
